### ISSUE TITLE
Sanity check please - Rails console

### ISSUE THREAD

**Issue by magpieuk** [myronmarston/mail_safe#6]
I love the mail safe gem and its a great tool, but can someone else please check to see whether it protects email sent from the console.

It seems to protect when running as a server but not from a console.

**Comment by myronmarston** [comment]
It should work fine from the rails console.  Mail safe itself doesn't know anything about the rails console; it simply does its job if it has been required, and has no effect if it has not been required.

Can you verify that mail safe has been required when you log into your rails console?  Here's what I see in my rails console:

``` ruby
 > $".select { |f| f =~ /mail_safe/ }
 => ["mail_safe/config.rb", "mail_safe/address_replacer.rb", "mail_safe/rails3_hook.rb", "mail_safe.rb"]
```

(`$"` is an array containing all files that have been required).

**Comment by magpieuk** [comment]
HI Myron

Yes I can confirm that it returns

["/home/irvingld/.rvm/gems/ruby-1.9.2-p180@global/gems/mail_safe-0.3.1/lib/mail_safe/config.rb",
"/home/irvingld/.rvm/gems/ruby-1.9.2-p180@global/gems/mail_safe-0.3.1/lib/mail_safe/address_replacer.rb",
"/home/irvingld/.rvm/gems/ruby-1.9.2-p180@global/gems/mail_safe-0.3.1/lib/mail_safe/rails3_hook.rb",
"/home/irvingld/.rvm/gems/ruby-1.9.2-p180@global/gems/mail_safe-0.3.1/lib/mail_safe.rb"]

But If call call Action Mailer from the console it sends out. I
thought it might be just me but wanted someone else to check.

On Fri, Oct 28, 2011 at 7:40 PM, Myron Marston
reply@reply.github.com
wrote:

**Comment by myronmarston** [comment]
What does this show in your console?

``` ruby
> Mail.send(:class_variable_get, '@@delivery_interceptors')
 => [MailSafe::MailInterceptor]
```

I'm thinking that maybe something is clearing the interceptors registered with Mail, including `mail_safe`.  that would explain it not working.

**Comment by magpieuk** [comment]
Thanks for taking the time with this myron.

Looks the same to me

> > Mail.send(:class_variable_get, '@@delivery_interceptors')
> > [MailSafe::MailInterceptor]

If you can do a simple test from a clean app and the problem is not there then it must be an issue with my config. I wasnt saying it was a problem, just I needed  a second pair of eyes.

**Comment by jjconti** [comment]
I tested it form rails console and works as expected.
