### ISSUE TITLE
Preserve address names

### ISSUE THREAD

**Issue by CodeMonkeySteve** [myronmarston/mail_safe#7]
Addresses of the form "Name user@domain" are converted to "user@domain", even when not replacing the address.  Need to preserve the address name, whether or not user/domain are replaced.

(note: this issue is just a reminder - I'll fix this, if you don't get around to fixing it first).

**Comment by myronmarston** [comment]
Have at it.  I'm not actively using mail_safe on any projects at the moment (and in fact, I'm not using rails on any current projects), so I'm unlikely to fix this anytime soon.

**Comment by jjconti** [comment]
Fixed in 0.3.2.
